### ISSUE TITLE
The cursor is hard to see

### ISSUE THREAD

**Issue by mohd874** [relastle/bluewery.vim#4]
Thank you for creating a nice color for vim. 

I am using GVIM 8.0.586 on Win 10. I find it really hard to find the cursor in both normal and insert mode. To find the cursor, I have to switch to visual mode where it is more visible.

Keep the good work. I really like it.

**Comment by relastle** [comment]
The problem is also reproduced in MacVim.

I was not able to notice such a critical bug because I use (Neo)Vim inside iterm2.

Thank you for the report, it will be fixed soon 🙏

**Comment by relastle** [comment]
Closed this issue because the problem seems to be fixed in https://github.com/relastle/bluewery.vim/pull/5

**Comment by mohd874** [comment]
Thanks for quick response. I will start using it.

keep good work.
